title: Hello, Wellcome to the most awesome page
author: RosyRomance
email: rosyromance@domain.com
description: > # this means to ignore newlines until "baseurl:"
  bala bala bala

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle
theme: minima
show_excerpts: true # set to false to remove excerpts on the homepage
